#!/usr/bin/bash
echo "IDS Marco Antonio Roca /UPB SCZ";
echo "Analizando las 5 ips que mas atacan al sistema Inicio de IP's";
grep -E -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' /var/log/auth.log | sort -n | uniq -c | sort -rn | head -5 

line=($(grep -E -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' /var/log/auth.log | sort -n | uniq -c | sort -rn | head -5 | awk {'print $2'}))



echo "Adicionando LOG a las conexiones al puerto 22 SSH";
iptables -I INPUT 1 -p tcp --dport 22 -j LOG --log-prefix "INTENTO DE ACCESO SSH  por IP's" --log-level 4
iptables -I INPUT 2 -p tcp --dport 22 -j DROP


echo "IP's Bloqueadas";
for ((i=0; i<${#line[@]};i++)) do iptables -I INPUT 1 -s ${line[i]} -j DROP; done
hostname=$(hostname -f)
iptables -D INPUT -s $hostname -j DROP

echo "TU HOSTNAME ES $hostname";
echo "Documentacion de logs almacenada en 'iptables.conf'";

iptables-save >> iptables.conf



